/**
 * Adds the TWV Tally Bridge tray app to Windows startup.
 *
 * Creates a VBScript launcher in:
 *   %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\
 *
 * VBScript is used so the console window is invisible when the tray app starts
 * at login (a direct .bat/.cmd shortcut would flash a console window).
 *
 * Run once: node dist/install-tray.js
 * Remove:   node dist/uninstall-tray.js
 */

import fs   from "fs";
import path from "path";

const STARTUP_DIR = path.join(
  process.env["APPDATA"] ?? "C:\\Users\\Default\\AppData\\Roaming",
  "Microsoft", "Windows", "Start Menu", "Programs", "Startup",
);
const VBS_NAME  = "twv-tray-startup.vbs";
const VBS_PATH  = path.join(STARTUP_DIR, VBS_NAME);
const TRAY_JS   = path.join(__dirname, "tray.js");
const NODE_PATH = process.execPath;  // full path to node.exe

function main(): void {
  if (!fs.existsSync(STARTUP_DIR)) {
    console.error(`Startup folder not found: ${STARTUP_DIR}`);
    process.exit(1);
  }

  // VBScript silently launches node tray.js with no console window
  const vbs = [
    `' TWV Tally Bridge — tray startup launcher`,
    `' Auto-generated by install-tray.js`,
    `Dim shell`,
    `Set shell = CreateObject("WScript.Shell")`,
    `shell.Run """${NODE_PATH}"" ""${TRAY_JS}""", 0, False`,
    `Set shell = Nothing`,
  ].join("\r\n");

  fs.writeFileSync(VBS_PATH, vbs, "utf-8");

  console.log(`✓ Tray startup installed.`);
  console.log(`  Launcher: ${VBS_PATH}`);
  console.log(`  Runs:     ${NODE_PATH} "${TRAY_JS}"`);
  console.log();
  console.log("The tray icon will appear automatically on next Windows login.");
  console.log("To start it now without rebooting, run:  node dist/tray.js");
}

main();
