/**
 * TWV Tally Bridge — System Tray App
 *
 * Shows bridge status as a coloured dot in the Windows taskbar notification area.
 *   Green  = healthy (Tally connected, no failures)
 *   Amber  = degraded (Tally disconnected OR pending/failed jobs)
 *   Red    = offline (bridge health endpoint unreachable)
 *
 * Left-click  → opens http://localhost:7788 in the browser
 * Right-click → context menu: Open Status Page | Refresh | ─── | Exit
 * Tooltip     → "TWV Bridge | Tally ✓ SDIPL | 3 pending | 12 today"
 *
 * Architecture:
 *   - This Node process polls http://localhost:7788/json every 30 s
 *   - Writes {tooltip, state} to a temp JSON file that PowerShell reads
 *   - Spawns a hidden PowerShell window that creates the NotifyIcon (Windows Forms)
 *   - When PS exits (user clicks Exit in the tray menu), this process also exits
 *
 * Run manually : node dist/tray.js
 * Auto-start   : node dist/install-tray.js   (adds to Windows startup)
 */

import { spawn } from "child_process";
import http       from "http";
import fs         from "fs";
import path       from "path";
import os         from "os";

const HEALTH_JSON  = "http://localhost:7788/json";
const STATUS_PAGE  = "http://localhost:7788";
const POLL_MS      = 30_000;
// Stable temp path — PS script watches this file
const STATUS_FILE  = path.join(os.tmpdir(), "twv-bridge-tray.json");
// PS helper written next to tray.js so it survives between runs
const PS_HELPER    = path.join(__dirname, "tray-helper.ps1");

// ── Health JSON shape ────────────────────────────────────────────────────────

interface HealthJson {
  version:          string;
  state:            "healthy" | "degraded" | "offline";
  tallyConnected:   boolean;
  tallyCompanyName: string | null;
  pendingCount:     number;
  failedCount:      number;
  completedToday:   number;
  lastSyncAt:       string | null;
  lastError:        string | null;
}

// ── Polling ──────────────────────────────────────────────────────────────────

async function fetchHealth(): Promise<HealthJson | null> {
  return new Promise((resolve) => {
    const req = http.get(HEALTH_JSON, { timeout: 5_000 }, (res) => {
      let body = "";
      res.on("data", (c: Buffer) => { body += c.toString(); });
      res.on("end", () => {
        try { resolve(JSON.parse(body) as HealthJson); }
        catch { resolve(null); }
      });
    });
    req.on("error", () => resolve(null));
    req.on("timeout", () => { req.destroy(); resolve(null); });
  });
}

function buildTooltip(h: HealthJson | null): string {
  if (!h) return "TWV Bridge — Offline";

  const parts: string[] = ["TWV Bridge"];
  parts.push(h.tallyConnected
    ? `Tally ✓${h.tallyCompanyName ? ` ${h.tallyCompanyName}` : ""}`
    : "Tally ✗ Disconnected");
  if (h.pendingCount > 0) parts.push(`${h.pendingCount} pending`);
  if (h.failedCount  > 0) parts.push(`${h.failedCount} failed`);
  if (h.completedToday > 0) parts.push(`${h.completedToday} today`);

  // Windows NotifyIcon tooltip limit: 63 chars
  const tip = parts.join(" | ");
  return tip.length > 63 ? tip.slice(0, 60) + "..." : tip;
}

function deriveState(h: HealthJson | null): "healthy" | "degraded" | "offline" {
  if (!h) return "offline";
  if (h.failedCount > 0 || !h.tallyConnected) return "degraded";
  return "healthy";
}

function writeStatus(tooltip: string, state: "healthy" | "degraded" | "offline"): void {
  try {
    fs.writeFileSync(STATUS_FILE, JSON.stringify({ tooltip, state }), "utf-8");
  } catch { /* ignore — PS script tolerates missing file */ }
}

async function poll(): Promise<void> {
  const h       = await fetchHealth();
  const tooltip = buildTooltip(h);
  const state   = deriveState(h);
  writeStatus(tooltip, state);
}

// ── PowerShell tray helper ───────────────────────────────────────────────────
// Written to disk once so it can be inspected / edited without rebuilding.

function writePsHelper(): void {
  // Using an array of lines avoids template-literal / PowerShell $ conflicts.
  const lines: string[] = [
    "# TWV Tally Bridge — System Tray Helper",
    "# Auto-generated by tray.js — do not edit manually.",
    `param([string]$StatusFile = "${STATUS_FILE.replace(/\\/g, "/")}",`,
    `      [string]$StatusPage = "${STATUS_PAGE}")`,
    "",
    "Add-Type -AssemblyName System.Windows.Forms",
    "Add-Type -AssemblyName System.Drawing",
    "",
    "# ── Icon factory: draws a filled 16x16 circle in the requested colour ────",
    "function New-StateIcon {",
    "  param([string]$State)",
    "  $bmp = New-Object System.Drawing.Bitmap(16,16)",
    "  $g   = [System.Drawing.Graphics]::FromImage($bmp)",
    "  $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias",
    "  $col = switch ($State) {",
    "    'healthy'  { [System.Drawing.Color]::FromArgb(74, 222, 128) }",
    "    'degraded' { [System.Drawing.Color]::FromArgb(251, 191, 36) }",
    "    default    { [System.Drawing.Color]::FromArgb(248, 113, 113) }",
    "  }",
    "  $brush = New-Object System.Drawing.SolidBrush($col)",
    "  $g.FillEllipse($brush, 1, 1, 14, 14)",
    "  $g.Dispose(); $brush.Dispose()",
    "  $hIcon = $bmp.GetHicon()",
    "  $bmp.Dispose()",
    "  return [System.Drawing.Icon]::FromHandle($hIcon)",
    "}",
    "",
    "# ── Tray icon setup ───────────────────────────────────────────────────────",
    "$script:currentState = 'loading'",
    "$script:prevState    = 'loading'",
    "",
    "$tray          = New-Object System.Windows.Forms.NotifyIcon",
    "$tray.Icon     = New-StateIcon 'offline'",
    "$tray.Text     = 'TWV Tally Bridge — loading...'",
    "$tray.Visible  = $true",
    "",
    "# ── Context menu ─────────────────────────────────────────────────────────",
    "$menu = New-Object System.Windows.Forms.ContextMenuStrip",
    "",
    "$openItem = $menu.Items.Add('Open Status Page')",
    "$openItem.add_Click({",
    "  [System.Diagnostics.Process]::Start($StatusPage) | Out-Null",
    "})",
    "",
    "$refreshItem = $menu.Items.Add('Refresh Now')",
    "$refreshItem.add_Click({ Update-TrayStatus })",
    "",
    "$menu.Items.Add([System.Windows.Forms.ToolStripSeparator]::new()) | Out-Null",
    "",
    "$exitItem = $menu.Items.Add('Exit Tray')",
    "$exitItem.add_Click({",
    "  $tray.Visible = $false",
    "  $tray.Dispose()",
    "  [System.Windows.Forms.Application]::Exit()",
    "})",
    "",
    "$tray.ContextMenuStrip = $menu",
    "",
    "# Left-click opens the status page",
    "$tray.add_MouseClick({",
    "  param($s, $e)",
    "  if ($e.Button -eq [System.Windows.Forms.MouseButtons]::Left) {",
    "    [System.Diagnostics.Process]::Start($StatusPage) | Out-Null",
    "  }",
    "})",
    "",
    "# ── Status update function ────────────────────────────────────────────────",
    "function Update-TrayStatus {",
    "  try {",
    "    if (-not (Test-Path $StatusFile)) { return }",
    "    $raw   = Get-Content $StatusFile -Raw -ErrorAction Stop",
    "    $data  = $raw | ConvertFrom-Json",
    "    $state = $data.state",
    "    $tip   = $data.tooltip",
    "    if ($tip.Length -gt 63) { $tip = $tip.Substring(0,60) + '...' }",
    "    $tray.Text = $tip",
    "    if ($state -ne $script:currentState) {",
    "      $script:prevState    = $script:currentState",
    "      $script:currentState = $state",
    "      $tray.Icon = New-StateIcon $state",
    "      # Balloon notification on state change",
    "      $icon = switch ($state) {",
    "        'offline'  { [System.Windows.Forms.ToolTipIcon]::Error }",
    "        'degraded' { [System.Windows.Forms.ToolTipIcon]::Warning }",
    "        default    { [System.Windows.Forms.ToolTipIcon]::Info }",
    "      }",
    "      $msg = switch ($state) {",
    "        'offline'  { 'Bridge is offline — sync paused' }",
    "        'degraded' { 'Bridge degraded — check status page' }",
    "        default    { 'Bridge is healthy' }",
    "      }",
    "      # Only notify when transitioning away from healthy, or back to healthy",
    "      if ($script:prevState -ne 'loading') {",
    "        $tray.ShowBalloonTip(3000, 'TWV Tally Bridge', $msg, $icon)",
    "      }",
    "    }",
    "  } catch {",
    "    # Swallow — file may not exist yet on first tick",
    "  }",
    "}",
    "",
    "# ── Timer: refresh every 30 s ─────────────────────────────────────────────",
    "$timer          = New-Object System.Windows.Forms.Timer",
    "$timer.Interval = 30000",
    "$timer.add_Tick({ Update-TrayStatus })",
    "$timer.Start()",
    "Update-TrayStatus   # immediate first update",
    "",
    "[System.Windows.Forms.Application]::Run()",
    "$tray.Visible = $false",
    "$tray.Dispose()",
  ];
  fs.writeFileSync(PS_HELPER, lines.join("\r\n"), "utf-8");
}

// ── Entry point ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  // Initial status file so PS has something to read on first tick
  writeStatus("TWV Tally Bridge — loading...", "offline");

  // Write the PowerShell helper next to tray.js
  writePsHelper();

  // Start polling
  await poll();
  const timer = setInterval(() => { void poll(); }, POLL_MS);

  // Spawn the PowerShell tray (hidden window — runs in the user's desktop session)
  const ps = spawn(
    "powershell.exe",
    [
      "-WindowStyle", "Hidden",
      "-NonInteractive",
      "-ExecutionPolicy", "Bypass",
      "-File", PS_HELPER,
    ],
    { stdio: "ignore", detached: false },
  );

  ps.on("exit", (code) => {
    clearInterval(timer);
    process.exit(code ?? 0);
  });

  process.on("SIGINT", () => {
    clearInterval(timer);
    ps.kill();
    process.exit(0);
  });

  process.on("SIGTERM", () => {
    clearInterval(timer);
    ps.kill();
    process.exit(0);
  });
}

main().catch((err) => {
  console.error("Tray startup failed:", err);
  process.exit(1);
});
