import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { logAudit } from "@/lib/audit";
import {
  getTemplateKey,
  mergeVariables,
  generateAgreementPdf,
} from "@/lib/agreement-generator";

/**
 * POST: Generate a new agreement for a case
 * PATCH: Update agreement status (internal approval, send to client, etc.)
 */

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: caseId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Fetch the case with all needed data
  const { data: caseData, error: caseError } = await supabase
    .from("cases")
    .select(
      "*, location:locations!cases_location_id_fkey(id, name, code, address, city, state)"
    )
    .eq("id", caseId)
    .single();

  if (caseError || !caseData) {
    return NextResponse.json({ error: "Case not found" }, { status: 404 });
  }

  // Validate case state
  if (!caseData.rate) {
    return NextResponse.json(
      { error: "Case rate must be set before generating an agreement" },
      { status: 400 }
    );
  }

  const { data: dbUser } = await supabase
    .from("users")
    .select("id")
    .eq("auth_id", user.id)
    .single();

  // Build template variables
  const templateKey = getTemplateKey(caseData.purpose);
  const location = caseData.location as { name: string; address?: string; city?: string; state?: string } | null;

  const locationAddress = [
    location?.address,
    location?.city,
    location?.state,
  ]
    .filter(Boolean)
    .join(", ") || "Chennai";

  const clientAddress = [
    caseData.client_address,
    caseData.client_city,
    caseData.client_state,
    caseData.client_pincode,
  ]
    .filter(Boolean)
    .join(", ");

  const variables = mergeVariables({
    agreementNumber: "", // Will be auto-generated by DB trigger
    agreementDate: new Date().toISOString(),
    clientName: caseData.client_name,
    clientCompanyName: caseData.client_company_name,
    clientEntityType: caseData.client_entity_type,
    clientAddress: clientAddress || "To be provided",
    clientGstNumber: caseData.client_gst_number,
    clientPanNumber: caseData.client_pan_number,
    clientCinNumber: caseData.client_cin_number,
    clientEmail: caseData.client_email,
    clientPhone: caseData.client_phone,
    locationName: location?.name || "The WorkVilla",
    locationAddress,
    purpose: caseData.purpose,
    rate: caseData.rate,
    tenureMonths: caseData.tenure_months || 12,
    startDate: caseData.start_date || new Date().toISOString(),
    securityDeposit: caseData.security_deposit || 0,
  });

  // Generate PDF
  const pdfDoc = generateAgreementPdf(templateKey, variables);
  const pdfBuffer = Buffer.from(pdfDoc.output("arraybuffer"));

  // Upload to Supabase Storage
  const storagePath = `case-agreements/${caseId}/${Date.now()}-agreement.pdf`;

  const { error: uploadError } = await supabase.storage
    .from("documents")
    .upload(storagePath, pdfBuffer, {
      contentType: "application/pdf",
      upsert: true,
    });

  if (uploadError) {
    return NextResponse.json(
      { error: "Failed to upload agreement PDF: " + uploadError.message },
      { status: 500 }
    );
  }

  // Create document record for the PDF
  const { data: docRecord } = await supabase
    .from("documents")
    .insert({
      title: `Agreement - ${caseData.client_name}`,
      file_name: `agreement-${caseId}.pdf`,
      file_path: storagePath,
      mime_type: "application/pdf",
      size_bytes: pdfBuffer.length,
      category: "case_document",
      uploaded_by: dbUser?.id,
    })
    .select("id")
    .single();

  // Create the agreement record
  const { data: agreement, error: agrError } = await supabase
    .from("case_agreements")
    .insert({
      case_id: caseId,
      template_key: templateKey,
      status: "draft",
      variables: variables as unknown as Record<string, unknown>,
      generated_document_id: docRecord?.id,
      valid_from: caseData.start_date,
      created_by: dbUser?.id,
    })
    .select("*")
    .single();

  if (agrError) {
    return NextResponse.json(
      { error: "Failed to create agreement: " + agrError.message },
      { status: 500 }
    );
  }

  // Link agreement to case
  if (agreement) {
    await supabase
      .from("cases")
      .update({
        agreement_id: agreement.id,
        agreement_status: "draft",
      })
      .eq("id", caseId);
  }

  // Audit
  if (dbUser?.id && agreement) {
    logAudit(supabase, {
      entityType: "case_agreement",
      entityId: agreement.id,
      action: "create",
      performedBy: dbUser.id,
      changes: { record: { old: null, new: agreement } },
    });
  }

  return NextResponse.json({ data: agreement }, { status: 201 });
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: caseId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json();
  const action = body.action as string;
  const agreementId = body.agreement_id as string;

  if (!agreementId) {
    return NextResponse.json(
      { error: "agreement_id is required" },
      { status: 400 }
    );
  }

  const { data: dbUser } = await supabase
    .from("users")
    .select("id")
    .eq("auth_id", user.id)
    .single();

  const updateData: Record<string, unknown> = {};

  switch (action) {
    case "approve_internally":
      updateData.status = "internally_approved";
      updateData.internal_approved_by = dbUser?.id;
      updateData.internal_approved_at = new Date().toISOString();
      break;

    case "send_to_client":
      updateData.status = "sent_to_client";
      updateData.sent_to_client_at = new Date().toISOString();
      updateData.sent_to_email = body.email;
      break;

    case "client_approved":
      updateData.status = "client_approved";
      updateData.client_approved_at = new Date().toISOString();
      break;

    case "initiate_signing":
      updateData.status = "signing";
      break;

    case "mark_executed":
      updateData.status = "executed";
      updateData.signed_at = new Date().toISOString();
      break;

    default:
      return NextResponse.json(
        { error: "Invalid action. Valid: approve_internally, send_to_client, client_approved, initiate_signing, mark_executed" },
        { status: 400 }
      );
  }

  const { data, error } = await supabase
    .from("case_agreements")
    .update(updateData)
    .eq("id", agreementId)
    .eq("case_id", caseId)
    .select("*")
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  // Also update the case's agreement_status
  if (data) {
    await supabase
      .from("cases")
      .update({ agreement_status: data.status })
      .eq("id", caseId);
  }

  // Audit
  if (dbUser?.id && data) {
    logAudit(supabase, {
      entityType: "case_agreement",
      entityId: agreementId,
      action: "update",
      performedBy: dbUser.id,
      changes: { action: { old: null, new: action }, status: { old: null, new: data.status } },
    });
  }

  return NextResponse.json({ data });
}
