import { NextRequest, NextResponse } from "next/server";
import { createClient, createAdminClient } from "@/lib/supabase/server";
import { logAudit } from "@/lib/audit";
import {
  getTemplateKey,
  mergeVariables,
  generateAgreementPdf,
} from "@/lib/agreement-generator";
import { resend, EMAIL_FROM, EMAIL_REPLY_TO } from "@/lib/mailer";
import { dltSms } from "@/lib/whatsapp";
import { checkVoExecutionPaymentGate } from "@/lib/vo-execution-gate";

/**
 * GET: Get agreement details with a signed URL for viewing the PDF
 * POST: Generate a new agreement for a case
 * PUT: Update agreement variables and regenerate PDF
 * PATCH: Update agreement status (internal approval, send to client, etc.)
 */

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: caseId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const adminSupabase = await createAdminClient();

  // Get the latest proposal for this case
  const { data: agreement, error } = await adminSupabase
    .from("case_agreements")
    .select("*, generated_document:documents!case_agreements_generated_document_id_fkey(file_path, file_name)")
    .eq("case_id", caseId)
    .eq("type", "proposal")
    .order("created_at", { ascending: false })
    .limit(1)
    .single();

  if (error || !agreement) {
    return NextResponse.json({ error: "No proposal found" }, { status: 404 });
  }

  // Generate signed URL for viewing the PDF
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const docRaw = agreement.generated_document as any;
  const doc = Array.isArray(docRaw) ? docRaw[0] : docRaw;
  let pdfUrl: string | null = null;

  if (doc?.file_path) {
    const { data: signedUrlData } = await adminSupabase.storage
      .from("crm-documents")
      .createSignedUrl(doc.file_path, 3600);
    pdfUrl = signedUrlData?.signedUrl || null;
  }

  return NextResponse.json({
    data: agreement,
    pdf_url: pdfUrl,
  });
}

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: caseId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Fetch the case with all needed data
  const { data: caseData, error: caseError } = await supabase
    .from("cases")
    .select(
      "*, location:locations!cases_location_id_fkey(id, name, code, address, city, state)"
    )
    .eq("id", caseId)
    .single();

  if (caseError || !caseData) {
    return NextResponse.json({ error: "Case not found" }, { status: 404 });
  }

  // Validate case state
  if (!caseData.rate) {
    return NextResponse.json(
      { error: "Case rate must be set before generating an agreement" },
      { status: 400 }
    );
  }

  const { data: dbUser } = await supabase
    .from("users")
    .select("id")
    .eq("auth_id", user.id)
    .single();

  // Build template variables
  const templateKey = getTemplateKey(caseData.purpose);
  const location = caseData.location as { name: string; address?: string; city?: string; state?: string } | null;

  const locationAddress = [
    location?.address,
    location?.city,
    location?.state,
  ]
    .filter(Boolean)
    .join(", ") || "Chennai";

  const clientAddress = [
    caseData.client_address,
    caseData.client_city,
    caseData.client_state,
    caseData.client_pincode,
  ]
    .filter(Boolean)
    .join(", ");

  const variables = mergeVariables({
    agreementNumber: "", // Will be auto-generated by DB trigger
    agreementDate: new Date().toISOString(),
    clientName: caseData.client_name,
    clientCompanyName: caseData.client_company_name,
    clientEntityType: caseData.client_entity_type,
    clientAddress: clientAddress || "To be provided",
    clientGstNumber: caseData.client_gst_number,
    clientPanNumber: caseData.client_pan_number,
    clientCinNumber: caseData.client_cin_number,
    clientEmail: caseData.client_email,
    clientPhone: caseData.client_phone,
    locationName: location?.name || "The WorkVilla",
    locationAddress,
    purpose: caseData.purpose,
    rate: caseData.rate,
    tenureMonths: caseData.tenure_months || 12,
    startDate: caseData.start_date || new Date().toISOString(),
    securityDeposit: caseData.security_deposit || 0,
  });

  // Generate PDF
  const pdfDoc = generateAgreementPdf(templateKey, variables);
  const pdfBuffer = Buffer.from(pdfDoc.output("arraybuffer"));

  // Upload to Supabase Storage (use admin client to bypass bucket RLS)
  const adminSupabase = await createAdminClient();
  const storagePath = `case-agreements/${caseId}/${Date.now()}-agreement.pdf`;

  const { error: uploadError } = await adminSupabase.storage
    .from("crm-documents")
    .upload(storagePath, pdfBuffer, {
      contentType: "application/pdf",
      upsert: true,
    });

  if (uploadError) {
    return NextResponse.json(
      { error: "Failed to upload agreement PDF: " + uploadError.message },
      { status: 500 }
    );
  }

  // Create document record for the PDF
  const { data: docRecord } = await supabase
    .from("documents")
    .insert({
      title: `Agreement - ${caseData.client_name}`,
      file_name: `agreement-${caseId}.pdf`,
      file_path: storagePath,
      mime_type: "application/pdf",
      size_bytes: pdfBuffer.length,
      category: "case_document",
      uploaded_by: dbUser?.id,
    })
    .select("id")
    .single();

  // Create the proposal record
  const { data: agreement, error: agrError } = await supabase
    .from("case_agreements")
    .insert({
      case_id: caseId,
      template_key: templateKey,
      type: "proposal",
      status: "draft",
      variables: variables as unknown as Record<string, unknown>,
      generated_document_id: docRecord?.id,
      valid_from: caseData.start_date,
      created_by: dbUser?.id,
    })
    .select("*")
    .single();

  if (agrError) {
    return NextResponse.json(
      { error: "Failed to create agreement: " + agrError.message },
      { status: 500 }
    );
  }

  // Link agreement to case
  if (agreement) {
    await supabase
      .from("cases")
      .update({
        agreement_id: agreement.id,
        agreement_status: "draft",
      })
      .eq("id", caseId);
  }

  // Audit
  if (dbUser?.id && agreement) {
    logAudit(supabase, {
      entityType: "case_agreement",
      entityId: agreement.id,
      action: "create",
      performedBy: dbUser.id,
      changes: { record: { old: null, new: agreement } },
    });
  }

  return NextResponse.json({ data: agreement }, { status: 201 });
}

/**
 * PUT: Update agreement variables and regenerate the PDF
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: caseId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json();
  const agreementId = body.agreement_id as string;
  const updatedVars = body.variables as Record<string, unknown>;

  if (!agreementId) {
    return NextResponse.json({ error: "agreement_id is required" }, { status: 400 });
  }

  const { data: dbUser } = await supabase
    .from("users")
    .select("id")
    .eq("auth_id", user.id)
    .single();

  // Fetch the existing agreement
  const { data: existingAgreement, error: fetchErr } = await supabase
    .from("case_agreements")
    .select("*")
    .eq("id", agreementId)
    .eq("case_id", caseId)
    .single();

  if (fetchErr || !existingAgreement) {
    return NextResponse.json({ error: "Agreement not found" }, { status: 404 });
  }

  // Only allow editing in draft or internally_approved states
  if (!["draft", "internally_approved"].includes(existingAgreement.status)) {
    return NextResponse.json(
      { error: "Agreement can only be edited in draft or internally approved state" },
      { status: 400 }
    );
  }

  // Merge existing variables with updated ones
  const existingVars = (existingAgreement.variables || {}) as Record<string, unknown>;
  const mergedVars = { ...existingVars, ...updatedVars };

  // Regenerate PDF with updated variables
  const templateKey = existingAgreement.template_key;
  const pdfDoc = generateAgreementPdf(templateKey, mergedVars as never);
  const pdfBuffer = Buffer.from(pdfDoc.output("arraybuffer"));

  const adminSupabase = await createAdminClient();
  const storagePath = `case-agreements/${caseId}/${Date.now()}-agreement.pdf`;

  const { error: uploadError } = await adminSupabase.storage
    .from("crm-documents")
    .upload(storagePath, pdfBuffer, {
      contentType: "application/pdf",
      upsert: true,
    });

  if (uploadError) {
    return NextResponse.json(
      { error: "Failed to upload regenerated PDF: " + uploadError.message },
      { status: 500 }
    );
  }

  // Create new document record
  const { data: docRecord } = await supabase
    .from("documents")
    .insert({
      title: `Agreement - ${mergedVars.client_name || "Client"}`,
      file_name: `agreement-${caseId}.pdf`,
      file_path: storagePath,
      mime_type: "application/pdf",
      size_bytes: pdfBuffer.length,
      category: "case_document",
      uploaded_by: dbUser?.id,
    })
    .select("id")
    .single();

  // Update the agreement with new variables and new PDF
  const { data: updated, error: updateErr } = await supabase
    .from("case_agreements")
    .update({
      variables: mergedVars,
      generated_document_id: docRecord?.id,
      status: "draft", // Reset to draft after edit
    })
    .eq("id", agreementId)
    .eq("case_id", caseId)
    .select("*")
    .single();

  if (updateErr) {
    return NextResponse.json({ error: updateErr.message }, { status: 500 });
  }

  // Update case agreement_status back to draft
  if (updated) {
    await supabase
      .from("cases")
      .update({ agreement_status: "draft" })
      .eq("id", caseId);
  }

  // Audit
  if (dbUser?.id && updated) {
    logAudit(supabase, {
      entityType: "case_agreement",
      entityId: agreementId,
      action: "update",
      performedBy: dbUser.id,
      changes: { action: { old: null, new: "edit_variables" }, variables: { old: existingVars, new: mergedVars } },
    });
  }

  return NextResponse.json({ data: updated });
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: caseId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json();
  const action = body.action as string;
  const agreementId = body.agreement_id as string;

  if (!agreementId) {
    return NextResponse.json(
      { error: "agreement_id is required" },
      { status: 400 }
    );
  }

  const { data: dbUser } = await supabase
    .from("users")
    .select("id, role")
    .eq("auth_id", user.id)
    .single();

  const ALLOWED_ROLES = ["admin", "manager", "sales_rep", "office_admin"];
  if (!dbUser || !ALLOWED_ROLES.includes(dbUser.role)) {
    return NextResponse.json({ error: "Not authorized to update agreement status" }, { status: 403 });
  }

  // Fetch current agreement to validate status transitions
  const { data: currentAgreement } = await supabase
    .from("case_agreements")
    .select("status, type, variables, agreement_number, template_key, generated_document:documents!case_agreements_generated_document_id_fkey(file_path, file_name)")
    .eq("id", agreementId)
    .eq("case_id", caseId)
    .single();

  if (!currentAgreement) {
    return NextResponse.json({ error: "Agreement not found" }, { status: 404 });
  }

  // Enforce valid status transitions
  const validTransitions: Record<string, string[]> = {
    approve_internally: ["draft"],
    send_to_client: ["internally_approved"],
    client_approved: ["sent_to_client"],
    initiate_signing: ["client_approved"],
    mark_executed: ["signing", "client_approved"],
  };

  if (validTransitions[action] && !validTransitions[action].includes(currentAgreement.status)) {
    return NextResponse.json(
      { error: `Cannot ${action.replace(/_/g, " ")} — agreement must be in ${validTransitions[action].join(" or ")} status (currently: ${currentAgreement.status})` },
      { status: 400 }
    );
  }

  // Prepaid aggregators and direct clients (no aggregator) both require a
  // paid VO case invoice before the Leave & License Agreement can execute —
  // see src/lib/case-invoicing.ts. This replaces the earlier manual
  // "approved Payment Proof document" gate with the real, Tally-issued
  // invoice's payment status.
  if (action === "mark_executed" && currentAgreement.type === "leave_license") {
    const gateError = await checkVoExecutionPaymentGate(supabase, caseId);
    if (gateError) {
      return NextResponse.json({ error: gateError }, { status: 400 });
    }
  }

  const updateData: Record<string, unknown> = {};

  switch (action) {
    case "approve_internally":
      updateData.status = "internally_approved";
      updateData.internal_approved_by = dbUser?.id;
      updateData.internal_approved_at = new Date().toISOString();
      break;

    case "send_to_client":
      updateData.status = "sent_to_client";
      updateData.sent_to_client_at = new Date().toISOString();
      updateData.sent_to_email = body.email;
      break;

    case "client_approved":
      updateData.status = "client_approved";
      updateData.client_approved_at = new Date().toISOString();
      break;

    case "initiate_signing":
      updateData.status = "signing";
      break;

    case "mark_executed":
      updateData.status = "executed";
      updateData.signed_at = new Date().toISOString();
      break;

    default:
      return NextResponse.json(
        { error: "Invalid action. Valid: approve_internally, send_to_client, client_approved, initiate_signing, mark_executed" },
        { status: 400 }
      );
  }

  const { data, error } = await supabase
    .from("case_agreements")
    .update(updateData)
    .eq("id", agreementId)
    .eq("case_id", caseId)
    .select("*")
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  // Also update the case's agreement_status
  if (data) {
    await supabase
      .from("cases")
      .update({ agreement_status: data.status })
      .eq("id", caseId);
  }

  // Send email to client when agreement is sent to them
  if (action === "send_to_client" && data) {
    try {
      const vars = (currentAgreement.variables || {}) as Record<string, unknown>;
      const clientEmail = String(vars.client_email || "");
      const clientName = String(vars.client_name || "Client");
      const agreementNumber = currentAgreement.agreement_number || data.agreement_number || "";
      const rateFormatted = String(vars.rate_formatted || vars.rate || "");
      const tenureMonths = String(vars.tenure_months || "");
      const startDateFormatted = String(vars.start_date_formatted || "");

      if (clientEmail) {
        const adminSupabase = await createAdminClient();

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const docRaw = currentAgreement.generated_document as any;
        const doc = Array.isArray(docRaw) ? docRaw[0] : docRaw;

        let pdfAttachment: { filename: string; content: Buffer; contentType: string } | undefined;
        if (doc?.file_path) {
          const { data: fileData } = await adminSupabase.storage
            .from("crm-documents")
            .download(doc.file_path);
          if (fileData) {
            const arrayBuffer = await fileData.arrayBuffer();
            pdfAttachment = {
              filename: `${agreementNumber || "Agreement"}.pdf`,
              content: Buffer.from(arrayBuffer),
              contentType: "application/pdf",
            };
          }
        }

        await resend.emails.send({
          from: EMAIL_FROM,
          replyTo: EMAIL_REPLY_TO,
          to: clientEmail,
          subject: `Your Virtual Office Agreement ${agreementNumber} - The WorkVilla`,
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
              <div style="background-color: #015E65; padding: 24px 32px;">
                <h1 style="color: #ffffff; margin: 0; font-size: 22px; font-weight: bold;">The WorkVilla</h1>
                <p style="color: #00AE6C; margin: 4px 0 0; font-size: 12px;">Empower your business with flexible workspaces</p>
              </div>
              <div style="padding: 32px;">
                <p style="color: #1a1b1e; font-size: 15px;">Dear ${clientName},</p>
                <p style="color: #333; font-size: 14px;">We are pleased to share your Virtual Office Agreement for The WorkVilla. Please find the agreement <strong>${agreementNumber}</strong> attached to this email.</p>
                <p style="color: #333; font-size: 14px;">Here is a summary of your agreement details:</p>
                <table style="border-collapse: collapse; margin: 20px 0; width: 100%; background: #f0faf5; border-radius: 6px;">
                  <tr><td style="padding: 10px 16px; color: #666; border-bottom: 1px solid #e5e7eb;">Agreement No.:</td><td style="padding: 10px 16px; font-weight: bold; color: #015E65; border-bottom: 1px solid #e5e7eb;">${agreementNumber}</td></tr>
                  ${rateFormatted ? `<tr><td style="padding: 10px 16px; color: #666; border-bottom: 1px solid #e5e7eb;">Monthly Fee:</td><td style="padding: 10px 16px; font-weight: bold; color: #015E65; border-bottom: 1px solid #e5e7eb;">${rateFormatted} + GST</td></tr>` : ""}
                  ${startDateFormatted ? `<tr><td style="padding: 10px 16px; color: #666; border-bottom: 1px solid #e5e7eb;">Start Date:</td><td style="padding: 10px 16px; color: #333; border-bottom: 1px solid #e5e7eb;">${startDateFormatted}</td></tr>` : ""}
                  ${tenureMonths ? `<tr><td style="padding: 10px 16px; color: #666;">Tenure:</td><td style="padding: 10px 16px; color: #333;">${tenureMonths} months</td></tr>` : ""}
                </table>
                <p style="color: #333; font-size: 14px;">Please review the attached agreement carefully. Once you have reviewed it, please confirm your acceptance so we can proceed with the next steps.</p>
                <p style="color: #333; font-size: 14px;">We look forward to supporting your business at The WorkVilla.</p>
                <p style="color: #333; font-size: 14px;">Warm regards,<br/><strong>The WorkVilla Team</strong></p>
                <p style="color: #666; font-size: 12px; margin-top: 16px;">For any queries, write to us at <a href="mailto:space@theworkvilla.com" style="color: #015E65;">space@theworkvilla.com</a> or call <strong>+91 97910 97900</strong>.</p>
              </div>
              <div style="background-color: #015E65; padding: 16px 32px; text-align: center;">
                <p style="color: #ffffff; margin: 0; font-size: 11px;">SREE DESIGN INFRASTRUCTURE PVT LTD</p>
                <p style="color: rgba(255,255,255,0.7); margin: 4px 0 0; font-size: 10px;">Prakash Presidium, 110, MG Road, Nungambakkam, Chennai - 600034 | +91 97910 97900</p>
                <p style="color: rgba(255,255,255,0.7); margin: 4px 0 0; font-size: 10px;">GST: 33AAACU4245J1ZF</p>
                <p style="color: #00AE6C; margin: 4px 0 0; font-size: 10px;">www.theworkvilla.com</p>
              </div>
            </div>
          `,
          attachments: pdfAttachment ? [pdfAttachment] : undefined,
        });
      }
    } catch (emailErr) {
      // Log but don't fail the status update
      console.error("Failed to send agreement email to client:", emailErr);
    }
  }

  // DLT SMS: Contract Welcome when agreement is executed
  if (action === "mark_executed" && data) {
    try {
      const vars = (currentAgreement.variables || {}) as Record<string, unknown>;
      const clientPhone = String(vars.client_phone || "");
      const clientName = String(vars.client_name || "Client");
      const startDate = vars.start_date_formatted
        ? String(vars.start_date_formatted)
        : vars.start_date
          ? new Date(String(vars.start_date)).toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata", day: "2-digit", month: "2-digit", year: "numeric" })
          : new Date().toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata", day: "2-digit", month: "2-digit", year: "numeric" });

      if (clientPhone && body.send_sms !== false) {
        dltSms.contractWelcome(clientPhone, clientName, startDate, caseId).catch(console.error);
      }
    } catch (smsErr) {
      console.error("Failed to send contract welcome SMS:", smsErr);
    }
  }

  // Audit
  if (dbUser?.id && data) {
    logAudit(supabase, {
      entityType: "case_agreement",
      entityId: agreementId,
      action: "update",
      performedBy: dbUser.id,
      changes: { action: { old: null, new: action }, status: { old: null, new: data.status } },
    });
  }

  return NextResponse.json({ data });
}
