import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { generateBillingStatementSchema } from "@/lib/validations";
import { logAudit } from "@/lib/audit";

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(request.url);
  const page = parseInt(searchParams.get("page") || "1");
  const limit = parseInt(searchParams.get("limit") || "25");
  const contractId = searchParams.get("contract_id");
  const leadId = searchParams.get("lead_id");
  const status = searchParams.get("status");

  const offset = (page - 1) * limit;

  let query = supabase
    .from("billing_statements")
    .select(
      "*, contract:contracts!billing_statements_contract_id_fkey(id, contract_number, title), lead:leads!billing_statements_lead_id_fkey(id, first_name, last_name, company)",
      { count: "exact" }
    );

  if (contractId) query = query.eq("contract_id", contractId);
  if (leadId) query = query.eq("lead_id", leadId);
  if (status) query = query.eq("status", status);

  query = query.order("created_at", { ascending: false }).range(offset, offset + limit - 1);

  const { data, error, count } = await query;
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  return NextResponse.json({
    data,
    pagination: { page, limit, total: count || 0, totalPages: Math.ceil((count || 0) / limit) },
  });
}

export async function POST(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await request.json();
  const result = generateBillingStatementSchema.safeParse(body);
  if (!result.success) {
    return NextResponse.json({ error: "Validation failed", details: result.error.issues }, { status: 400 });
  }

  // Fetch the contract — must exist
  const { data: contract, error: contractError } = await supabase
    .from("contracts")
    .select("id, lead_id, total_amount, tax_percentage")
    .eq("id", result.data.contract_id)
    .single();

  if (contractError || !contract) {
    return NextResponse.json({ error: "Contract not found" }, { status: 404 });
  }

  const { data: dbUser } = await supabase.from("users").select("id").eq("auth_id", user.id).single();

  // Fixed amount from the contract's recurring amount
  const fixedAmount = contract.total_amount || 0;

  // Fetch all pending usage charges for this contract within the billing period
  const { data: usageCharges, error: usageError } = await supabase
    .from("usage_charges")
    .select("id, total")
    .eq("contract_id", result.data.contract_id)
    .gte("charge_date", result.data.period_start)
    .lte("charge_date", result.data.period_end)
    .eq("status", "pending");

  if (usageError) return NextResponse.json({ error: usageError.message }, { status: 500 });

  // Calculate totals
  const usageAmount = (usageCharges || []).reduce((sum, charge) => sum + (charge.total || 0), 0);
  const subtotal = fixedAmount + usageAmount;
  const taxPercentage = contract.tax_percentage || 0;
  const taxAmount = subtotal * (taxPercentage / 100);
  const totalAmount = subtotal + taxAmount;

  // Insert billing statement (statement_number is auto-generated by DB trigger)
  const { data: statement, error: insertError } = await supabase
    .from("billing_statements")
    .insert({
      contract_id: result.data.contract_id,
      lead_id: contract.lead_id,
      period_start: result.data.period_start,
      period_end: result.data.period_end,
      fixed_amount: fixedAmount,
      usage_amount: usageAmount,
      subtotal,
      tax_percentage: taxPercentage,
      tax_amount: taxAmount,
      total_amount: totalAmount,
      status: "draft",
      notes: result.data.notes,
      created_by: dbUser?.id,
    })
    .select("*")
    .single();

  if (insertError) return NextResponse.json({ error: insertError.message }, { status: 500 });

  // Update all fetched usage charges: set status → "billed" and link to this statement
  if (usageCharges && usageCharges.length > 0) {
    const chargeIds = usageCharges.map((c) => c.id);
    const { error: updateError } = await supabase
      .from("usage_charges")
      .update({ status: "billed", billing_statement_id: statement.id })
      .in("id", chargeIds);

    if (updateError) {
      return NextResponse.json({ error: updateError.message }, { status: 500 });
    }
  }

  if (statement && dbUser?.id) {
    logAudit(supabase, {
      entityType: "billing_statement",
      entityId: statement.id,
      action: "create",
      performedBy: dbUser.id,
      changes: { record: { old: null, new: statement } },
    });
  }

  return NextResponse.json({ data: statement }, { status: 201 });
}
