-- Add 'viewer' to the user_role enum.
-- Viewers have read-only access to all menus except Admin/Settings.
--
-- NOTE: this file's content and 00178_viewer_role_enum.sql's content are
-- swapped relative to what their filenames say. ALTER TYPE ... ADD VALUE
-- cannot be used in the same transaction that adds it (see 00058, 00093,
-- 00115 for the same convention), but the rent-management policies in what
-- is now 00178 reference 'viewer' — so the enum addition has to run first,
-- under the lower migration number. Renaming either file was not an option:
-- both numbers are already applied in production, and
-- check-migration-numbers.mjs verifies the recorded name for an applied
-- version against the on-disk filename, so the filenames had to stay put.
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'viewer';
