-- Accounts Receivable foundation.
-- Adds explicit payment due date + reminder tracking to billing_statements so
-- the new /accounting/receivables page can age by due_date (not statement
-- period) and the upcoming payment-reminder cron (PR B) can throttle sends.
--
-- No backfill for existing statements (per ops decision): legacy statements
-- will display "—" for due date in the AR view. Going forward, every new
-- proforma generated by src/lib/billing.ts will set due_date.

ALTER TABLE billing_statements
  ADD COLUMN IF NOT EXISTS due_date date,
  ADD COLUMN IF NOT EXISTS last_reminder_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS reminder_count int NOT NULL DEFAULT 0;

COMMENT ON COLUMN billing_statements.due_date IS
  'Customer payment due date. Set by generators to period_end + 7 days. Used for aging buckets and the payment-reminder cron.';
COMMENT ON COLUMN billing_statements.last_reminder_sent_at IS
  'When the last customer payment reminder was emailed/WhatsApped. NULL = no reminder yet. Used to throttle the reminder cron (no two sends within 48h).';
COMMENT ON COLUMN billing_statements.reminder_count IS
  'How many customer reminders have been sent for this statement. Reset to 0 on payment_status=paid.';

-- Fast AR query: "which statements are unpaid and due / overdue?"
CREATE INDEX IF NOT EXISTS idx_billing_statements_ar_aging
  ON billing_statements (payment_status, due_date)
  WHERE payment_status IN ('unpaid', 'partially_paid');
