-- Link aggregator_invoices (existing postpaid UI/reconciliation record) to its
-- billing_statements counterpart, which is what Accounts Receivable, Ageing,
-- and the Tally Inbox actually read from. Going forward every new
-- aggregator_invoices row generated by generateConsolidatedInvoice() also
-- creates a billing_statements row and stamps this FK. Historical rows are
-- intentionally left NULL — those periods are already closed out via the
-- existing manual paid_at/status fields on aggregator_invoices itself; no
-- backfill.

ALTER TABLE aggregator_invoices
  ADD COLUMN billing_statement_id UUID REFERENCES billing_statements(id) ON DELETE SET NULL;

CREATE INDEX idx_agg_invoices_billing_statement
  ON aggregator_invoices(billing_statement_id)
  WHERE billing_statement_id IS NOT NULL;
