/**
 * src/lib/tally/enqueue.ts
 *
 * routeGstGenerationToTally — the single decision point for "should this GST
 * invoice be generated by Tally instead of the CRM?"
 *
 * Called at the THREE GST-generation entry points (dispatchGstDirect,
 * generate-gst-invoice, convert-to-gst-early). NOT at finalize — proforma_first
 * statements generate their GST invoice AFTER the PI is paid, not at finalize.
 *
 *   returns true  → routed to Tally (caller MUST skip its own CRM GST generation)
 *   returns false → CRM should generate the GST invoice as it does today
 *
 * Decide-once (D2): when routing to Tally, we STAMP issuance_channel='tally' on
 * the statement so every downstream step (delivery, reminder, void, reconcile)
 * branches on the stamp, not the live switch — immune to a mid-run switch flip.
 *
 * Idempotent (D3): one sales_voucher job per statement (idempotency_key); a
 * second call is a no-op.
 *
 * The PI flow (dispatchProforma) never calls this — proforma issuance stays CRM.
 */

import { createAdminClient } from "@/lib/supabase/server";
import type { SupabaseClient } from "@supabase/supabase-js";

/** Cheap check: is CRM GST issuance enabled right now? */
export async function isCrmGstEnabled(admin: SupabaseClient): Promise<boolean> {
  const { data } = await admin
    .from("app_settings")
    .select("value")
    .eq("key", "crm_gst_enabled")
    .single();
  return data?.value === "true";
}

/** Cheap check: is Tally the GST-invoice issuer right now? (master switch ON) */
export async function isTallyIssuanceActive(admin: SupabaseClient): Promise<boolean> {
  const { data } = await admin
    .from("app_settings")
    .select("value")
    .eq("key", "tally_sync_enabled")
    .single();
  return data?.value === "true";
}

/** Does this statement's GST invoice belong to Tally? (reads the stamp, not the switch) */
export async function isTallyIssuedStatement(
  admin: SupabaseClient,
  statementId: string,
): Promise<boolean> {
  const { data } = await admin
    .from("billing_statements")
    .select("issuance_channel")
    .eq("id", statementId)
    .single();
  return (data as { issuance_channel?: string } | null)?.issuance_channel === "tally";
}

/**
 * If Tally issuance is active, stamp the statement + enqueue the sales voucher
 * job and return true (caller skips CRM GST generation). Otherwise return false.
 *
 * Never throws — a Tally-side failure must never break the billing API.
 */
export async function routeGstGenerationToTally(statementId: string): Promise<boolean> {
  try {
    const admin = createAdminClient();

    if (!(await isTallyIssuanceActive(admin))) {
      return false; // sync OFF → CRM generates the GST invoice exactly as today
    }

    // Load the values the bridge needs (taxable values only — Tally computes tax, D8).
    const { data: stmt } = await admin
      .from("billing_statements")
      .select("id, subtotal, tax_percentage, line_items")
      .eq("id", statementId)
      .single();

    if (!stmt) {
      console.error("[tally/route] statement not found:", statementId);
      return false; // can't route — let CRM handle it rather than drop the invoice
    }

    // Best-effort: build a payment summary so the Tally user can see payment details
    // in the voucher narration before triggering IRN — avoids manual cross-checking.
    let paymentNarration: string | null = null;
    try {
      const { data: payments } = await admin
        .from("billing_payments")
        .select("amount, payment_mode, payment_reference")
        .eq("billing_statement_id", statementId)
        .order("payment_date", { ascending: true });

      if (payments && payments.length > 0) {
        const modeLabel: Record<string, string> = {
          cash: "Cash", upi: "UPI", card: "Card",
          bank_transfer: "Bank Transfer", razorpay: "Online (Razorpay)",
        };
        const parts = (payments as Array<{ amount: number; payment_mode: string; payment_reference: string | null }>)
          .map(p => {
            const amt = `Rs.${Math.round(Number(p.amount))}`;
            const mode = modeLabel[p.payment_mode] ?? p.payment_mode;
            const ref = p.payment_reference?.trim();
            return ref ? `${amt} via ${mode} (Ref: ${ref})` : `${amt} via ${mode}`;
          });
        paymentNarration = parts.length === 1
          ? `Paid: ${parts[0]}`
          : `Paid: ${parts.join(" + ")}`;
      }
    } catch {
      // best-effort — missing narration never blocks invoice creation
    }

    // Stamp issuance_channel='tally' ONCE (decide-once) + queued lifecycle.
    await admin
      .from("billing_statements")
      .update({
        issuance_channel:  "tally",
        tally_sync_status: "pending",
        lifecycle_stage:   "queued",
      })
      .eq("id", statementId);

    // Enqueue the sales-voucher job (idempotent — one per statement).
    const { error } = await admin.from("tally_sync_jobs").insert({
      job_type:             "sales_voucher",
      billing_statement_id: statementId,
      idempotency_key:      `sales_voucher:${statementId}`,
      status:               "pending",
      payload: {
        billing_statement_id: statementId,
        taxable_amount:       (stmt as { subtotal: number }).subtotal,
        tax_percentage:       (stmt as { tax_percentage: number }).tax_percentage,
        line_items:           (stmt as { line_items: unknown }).line_items,
        ...(paymentNarration ? { payment_narration: paymentNarration } : {}),
      },
    });

    if (error && error.code !== "23505") {
      // 23505 = unique violation = already queued = fine. Any other error: the
      // statement is stamped 'tally' but the job didn't queue — surface it.
      console.error("[tally/route] failed to enqueue sales_voucher:", error.message);
    }

    return true; // routed to Tally — caller must NOT generate a CRM GST invoice
  } catch (err) {
    console.error("[tally/route] unexpected error:", err);
    return false; // fail safe → let the CRM path proceed rather than drop the invoice
  }
}

/**
 * Reverse-sync a payment INTO Tally as a receipt voucher (closes the loop so
 * Tally's books show the payment the CRM recorded).
 *
 * Fires only when:
 *   • Tally sync is active (master switch ON), AND
 *   • the statement's GST invoice was issued by Tally (issuance_channel='tally'
 *     with a real tally_invoice_number) — there's nothing to reconcile against
 *     for a CRM-issued invoice.
 *
 * Idempotent: one receipt_voucher job per payment (idempotency_key keyed on the
 * payment id), so re-recording or a retry never double-posts a receipt.
 *
 * NOTE: the bridge's postReceiptVoucher is not built yet (needs a real Tally
 * receipt-voucher XML sample). Until then this job sits 'pending' harmlessly
 * while sync is paused. Build that before go-live, or these queue without effect.
 *
 * Never throws — a reverse-sync failure must never break payment recording.
 */
/**
 * Maps a TDS section code (as stored in tds_sections.code) to the Tally ledger
 * name the receipt voucher should credit for the TDS portion.
 *
 * Keys must match the tds_sections seed values exactly (194C, 194H, 194I_a,
 * 194I_b, 194J_a, 194J_b). Update values to match your Tally chart of accounts
 * before go-live — the bridge uses tds_ledger from the job payload directly.
 */
// All TDS deducted by customers flows into a single ledger in this company's
// chart of accounts (confirmed from Master.xml / Tally ledger report).
// All section codes point to the same ledger — do NOT split by section here.
const TDS_RECEIVABLE_LEDGER = "TDS Paid (Deducted by the Party)";

const TDS_LEDGER_MAP: Record<string, string> = {
  "194C":   TDS_RECEIVABLE_LEDGER,
  "194H":   TDS_RECEIVABLE_LEDGER,
  "194I":   TDS_RECEIVABLE_LEDGER,
  "194J":   TDS_RECEIVABLE_LEDGER,
  "194I_a": TDS_RECEIVABLE_LEDGER,
  "194I_b": TDS_RECEIVABLE_LEDGER,
  "194J_a": TDS_RECEIVABLE_LEDGER,
  "194J_b": TDS_RECEIVABLE_LEDGER,
};

function deriveTdsLedger(sectionCode: string | null | undefined): string | null {
  if (!sectionCode) return null;
  return TDS_LEDGER_MAP[sectionCode] ?? `TDS Receivable ${sectionCode}`;
}

export async function enqueueTallyReceiptVoucher(
  statementId: string,
  payment: {
    paymentId: string;
    amount: number;
    date: string;
    mode: string;
    reference?: string | null;
    tdsAmount?: number;
    /** TDS section code from tds_sections.code — used to derive the Tally ledger name */
    tdsSection?: string | null;
  },
): Promise<void> {
  try {
    const admin = createAdminClient();
    if (!(await isTallyIssuanceActive(admin))) return;

    const { data: stmt } = await admin
      .from("billing_statements")
      .select("id, issuance_channel, tally_invoice_number, tally_voucher_guid, contract:contracts!billing_statements_contract_id_fkey(lead:leads!contracts_lead_id_fkey(company, first_name, last_name))")
      .eq("id", statementId)
      .single();

    const s = stmt as {
      issuance_channel?: string;
      tally_invoice_number?: string | null;
      tally_voucher_guid?: string | null;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      contract?: any;
    } | null;

    // Only Tally-issued invoices have a Tally voucher to receipt against.
    if (!s || s.issuance_channel !== "tally" || !s.tally_invoice_number) return;

    const lead = s.contract?.lead;
    const partyName = lead?.company
      || `${lead?.first_name || ""} ${lead?.last_name || ""}`.trim()
      || "Customer";

    const tdsAmt  = Math.max(0, payment.tdsAmount || 0);
    const tdsSec  = payment.tdsSection ?? null;
    const tdsLedger = tdsAmt > 0 ? deriveTdsLedger(tdsSec) : null;

    const { error } = await admin.from("tally_sync_jobs").insert({
      job_type:             "receipt_voucher",
      billing_statement_id: statementId,
      idempotency_key:      `receipt_voucher:${payment.paymentId}`,
      status:               "pending",
      payload: {
        billing_statement_id: statementId,
        tally_invoice_number: s.tally_invoice_number,
        tally_voucher_guid:   s.tally_voucher_guid ?? null,
        payment_id:           payment.paymentId,   // so the ack can mirror back onto billing_payments
        party_name:           partyName,
        amount:               payment.amount,      // net cash received
        tds_amount:           tdsAmt,              // customer's TDS deduction (0 = none)
        tds_section:          tdsSec,              // e.g. "194I_b" — for reference/audit
        tds_ledger:           tdsLedger,           // resolved Tally ledger name for the bridge
        payment_date:         payment.date,
        payment_mode:         payment.mode,
        payment_reference:    payment.reference ?? null,
      },
    });

    if (error && error.code !== "23505") {
      console.error("[tally/receipt] failed to enqueue receipt_voucher:", error.message);
    }
  } catch (err) {
    console.error("[tally/receipt] unexpected error:", err);
  }
}

/**
 * Enqueue Tally receipts for EVERY recorded payment on a statement that hasn't
 * been synced yet. Used at Tally-issuance time for the proforma_first flow: a PI
 * is paid BEFORE the GST invoice exists, so the per-payment receipt enqueue
 * (above) no-ops at payment time (not yet Tally-issued). Once the invoice is
 * issued in Tally, this back-fills the receipt(s) so the money-in is recorded and
 * the party balance clears. Idempotent (one job per payment id).
 */
export async function enqueueReceiptsForPaidStatement(statementId: string): Promise<void> {
  try {
    const admin = createAdminClient();
    if (!(await isTallyIssuanceActive(admin))) return;

    const { data: payments } = await admin
      .from("billing_payments")
      .select("id, amount, tds_amount, tds_section, payment_date, payment_mode, payment_reference, tally_receipt_number")
      .eq("billing_statement_id", statementId);

    for (const p of (payments ?? []) as Array<{
      id: string; amount: number; tds_amount: number | null; tds_section: string | null;
      payment_date: string; payment_mode: string; payment_reference: string | null;
      tally_receipt_number: string | null;
    }>) {
      if (p.tally_receipt_number) continue;   // already synced
      await enqueueTallyReceiptVoucher(statementId, {
        paymentId:  p.id,
        amount:     Number(p.amount),
        tdsAmount:  Number(p.tds_amount || 0),
        tdsSection: p.tds_section,
        date:       p.payment_date,
        mode:       p.payment_mode,
        reference:  p.payment_reference,
      });
    }
  } catch (err) {
    console.error("[tally/receipt] back-fill error:", err);
  }
}

export type CreditNoteResult =
  | { ok: true }
  | { ok: false; reason: "sync_off" | "not_tally" | "not_found" | "error" };

/**
 * Enqueue a Credit Note to REVERSE a Tally-issued invoice (CRM-first cancel, Phase 1b).
 *
 * A Tally invoice is on Tally's books, so the CRM can't just void it. This queues a
 * credit_note job; the bridge posts a Credit Note in Tally reversing the invoice, and
 * only on confirmation does the ack mark the statement voided + un-link its charges
 * (Tally reverses first, CRM follows — books stay in sync).
 *
 * Returns a typed result so the cancel endpoint can give a precise error:
 *   - sync_off  → the bridge is paused; can't reverse in Tally right now
 *   - not_tally → this statement wasn't issued by Tally (use the normal CRM void)
 * Stamps lifecycle_stage='cancelling'. Idempotent (one credit_note job per statement).
 */
export async function enqueueTallyCreditNote(
  statementId: string,
  reason: string,
): Promise<CreditNoteResult> {
  try {
    const admin = createAdminClient();
    if (!(await isTallyIssuanceActive(admin))) return { ok: false, reason: "sync_off" };

    const { data: stmt } = await admin
      .from("billing_statements")
      .select(`
        id, issuance_channel, tally_invoice_number, tally_voucher_guid,
        subtotal, tax_percentage, line_items, statement_number, gst_invoice_date,
        contract:contracts!billing_statements_contract_id_fkey(
          contract_number,
          lead:leads!contracts_lead_id_fkey(company, first_name, last_name, gst_number)
        )
      `)
      .eq("id", statementId)
      .single();

    const s = stmt as {
      issuance_channel?: string;
      tally_invoice_number?: string | null;
      tally_voucher_guid?: string | null;
      subtotal?: number;
      tax_percentage?: number;
      line_items?: unknown;
      statement_number?: string;
      gst_invoice_date?: string | null;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      contract?: any;
    } | null;

    if (!s) return { ok: false, reason: "not_found" };
    if (s.issuance_channel !== "tally" || !s.tally_invoice_number) return { ok: false, reason: "not_tally" };

    const lead = s.contract?.lead;
    const partyName = lead?.company
      || `${lead?.first_name || ""} ${lead?.last_name || ""}`.trim()
      || "Customer";

    // Stamp cancelling so the UI + crons know a reversal is in flight.
    await admin
      .from("billing_statements")
      .update({ lifecycle_stage: "cancelling", tally_sync_status: "pending" })
      .eq("id", statementId);

    const { error } = await admin.from("tally_sync_jobs").insert({
      job_type:             "credit_note",
      billing_statement_id: statementId,
      idempotency_key:      `credit_note:${statementId}`,
      status:               "pending",
      payload: {
        billing_statement_id:   statementId,
        original_invoice_number: s.tally_invoice_number,
        original_invoice_date:   s.gst_invoice_date ?? null,
        original_voucher_guid:   s.tally_voucher_guid ?? null,
        taxable_amount:          s.subtotal,
        tax_percentage:          s.tax_percentage,
        line_items:              s.line_items,
        party_name:              partyName,
        buyer_gstin:             (lead?.gst_number as string | null) ?? "",
        reason,
      },
    });

    if (error && error.code !== "23505") {
      console.error("[tally/credit-note] failed to enqueue credit_note:", error.message);
      return { ok: false, reason: "error" };
    }
    return { ok: true };
  } catch (err) {
    console.error("[tally/credit-note] unexpected error:", err);
    return { ok: false, reason: "error" };
  }
}
