/**
 * src/lib/tally/enqueue.ts
 *
 * routeGstGenerationToTally — the single decision point for "should this GST
 * invoice be generated by Tally instead of the CRM?"
 *
 * Called at the THREE GST-generation entry points (dispatchGstDirect,
 * generate-gst-invoice, convert-to-gst-early). NOT at finalize — proforma_first
 * statements generate their GST invoice AFTER the PI is paid, not at finalize.
 *
 *   returns true  → routed to Tally (caller MUST skip its own CRM GST generation)
 *   returns false → CRM should generate the GST invoice as it does today
 *
 * Decide-once (D2): when routing to Tally, we STAMP issuance_channel='tally' on
 * the statement so every downstream step (delivery, reminder, void, reconcile)
 * branches on the stamp, not the live switch — immune to a mid-run switch flip.
 *
 * Idempotent (D3): one sales_voucher job per statement (idempotency_key); a
 * second call is a no-op.
 *
 * The PI flow (dispatchProforma) never calls this — proforma issuance stays CRM.
 */

import { createAdminClient } from "@/lib/supabase/server";
import type { SupabaseClient } from "@supabase/supabase-js";

/** Cheap check: is Tally the GST-invoice issuer right now? (master switch ON) */
export async function isTallyIssuanceActive(admin: SupabaseClient): Promise<boolean> {
  const { data } = await admin
    .from("app_settings")
    .select("value")
    .eq("key", "tally_sync_enabled")
    .single();
  return data?.value === "true";
}

/** Does this statement's GST invoice belong to Tally? (reads the stamp, not the switch) */
export async function isTallyIssuedStatement(
  admin: SupabaseClient,
  statementId: string,
): Promise<boolean> {
  const { data } = await admin
    .from("billing_statements")
    .select("issuance_channel")
    .eq("id", statementId)
    .single();
  return (data as { issuance_channel?: string } | null)?.issuance_channel === "tally";
}

/**
 * If Tally issuance is active, stamp the statement + enqueue the sales voucher
 * job and return true (caller skips CRM GST generation). Otherwise return false.
 *
 * Never throws — a Tally-side failure must never break the billing API.
 */
export async function routeGstGenerationToTally(statementId: string): Promise<boolean> {
  try {
    const admin = createAdminClient();

    if (!(await isTallyIssuanceActive(admin))) {
      return false; // sync OFF → CRM generates the GST invoice exactly as today
    }

    // Load the values the bridge needs (taxable values only — Tally computes tax, D8).
    const { data: stmt } = await admin
      .from("billing_statements")
      .select("id, subtotal, tax_percentage, line_items")
      .eq("id", statementId)
      .single();

    if (!stmt) {
      console.error("[tally/route] statement not found:", statementId);
      return false; // can't route — let CRM handle it rather than drop the invoice
    }

    // Stamp issuance_channel='tally' ONCE (decide-once) + queued lifecycle.
    await admin
      .from("billing_statements")
      .update({
        issuance_channel:  "tally",
        tally_sync_status: "pending",
        lifecycle_stage:   "queued",
      })
      .eq("id", statementId);

    // Enqueue the sales-voucher job (idempotent — one per statement).
    const { error } = await admin.from("tally_sync_jobs").insert({
      job_type:             "sales_voucher",
      billing_statement_id: statementId,
      idempotency_key:      `sales_voucher:${statementId}`,
      status:               "pending",
      payload: {
        billing_statement_id: statementId,
        taxable_amount:       (stmt as { subtotal: number }).subtotal,
        tax_percentage:       (stmt as { tax_percentage: number }).tax_percentage,
        line_items:           (stmt as { line_items: unknown }).line_items,
      },
    });

    if (error && error.code !== "23505") {
      // 23505 = unique violation = already queued = fine. Any other error: the
      // statement is stamped 'tally' but the job didn't queue — surface it.
      console.error("[tally/route] failed to enqueue sales_voucher:", error.message);
    }

    return true; // routed to Tally — caller must NOT generate a CRM GST invoice
  } catch (err) {
    console.error("[tally/route] unexpected error:", err);
    return false; // fail safe → let the CRM path proceed rather than drop the invoice
  }
}

/**
 * Reverse-sync a payment INTO Tally as a receipt voucher (closes the loop so
 * Tally's books show the payment the CRM recorded).
 *
 * Fires only when:
 *   • Tally sync is active (master switch ON), AND
 *   • the statement's GST invoice was issued by Tally (issuance_channel='tally'
 *     with a real tally_invoice_number) — there's nothing to reconcile against
 *     for a CRM-issued invoice.
 *
 * Idempotent: one receipt_voucher job per payment (idempotency_key keyed on the
 * payment id), so re-recording or a retry never double-posts a receipt.
 *
 * NOTE: the bridge's postReceiptVoucher is not built yet (needs a real Tally
 * receipt-voucher XML sample). Until then this job sits 'pending' harmlessly
 * while sync is paused. Build that before go-live, or these queue without effect.
 *
 * Never throws — a reverse-sync failure must never break payment recording.
 */
export async function enqueueTallyReceiptVoucher(
  statementId: string,
  payment: { paymentId: string; amount: number; date: string; mode: string; reference?: string | null },
): Promise<void> {
  try {
    const admin = createAdminClient();
    if (!(await isTallyIssuanceActive(admin))) return;

    const { data: stmt } = await admin
      .from("billing_statements")
      .select("id, issuance_channel, tally_invoice_number, tally_voucher_guid, contract:contracts!billing_statements_contract_id_fkey(lead:leads!contracts_lead_id_fkey(company, first_name, last_name))")
      .eq("id", statementId)
      .single();

    const s = stmt as {
      issuance_channel?: string;
      tally_invoice_number?: string | null;
      tally_voucher_guid?: string | null;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      contract?: any;
    } | null;

    // Only Tally-issued invoices have a Tally voucher to receipt against.
    if (!s || s.issuance_channel !== "tally" || !s.tally_invoice_number) return;

    const lead = s.contract?.lead;
    const partyName = lead?.company
      || `${lead?.first_name || ""} ${lead?.last_name || ""}`.trim()
      || "Customer";

    const { error } = await admin.from("tally_sync_jobs").insert({
      job_type:             "receipt_voucher",
      billing_statement_id: statementId,
      idempotency_key:      `receipt_voucher:${payment.paymentId}`,
      status:               "pending",
      payload: {
        billing_statement_id: statementId,
        tally_invoice_number: s.tally_invoice_number,
        tally_voucher_guid:   s.tally_voucher_guid ?? null,
        payment_id:           payment.paymentId,   // so the ack can mirror back onto billing_payments
        party_name:           partyName,
        amount:               payment.amount,
        payment_date:         payment.date,
        payment_mode:         payment.mode,
        payment_reference:    payment.reference ?? null,
      },
    });

    if (error && error.code !== "23505") {
      console.error("[tally/receipt] failed to enqueue receipt_voucher:", error.message);
    }
  } catch (err) {
    console.error("[tally/receipt] unexpected error:", err);
  }
}
